executable: count-words.c
	gcc -g -m32 -Wall -o count-words count-words.c

# count-words.o:
# 	gcc -g -m32 -Wall -c -o count-words.o count-words.c

# base.o:
# 	gcc -g -m32 -Wall -c -o base.o base.c 

# addresses.o:
# 	gcc -g -m32 -Wall -c -o addresses.o addresses.c

clean:
	rm -rf *.o